menu:
    Blog: /
    Archive: /archives/
    # Tags: /tags/
    # Categories: /categories/
    GitHub: https://github.com/wangbinyq
    Rss: /atom.xml

favicon: /favicon.png
logo: /logo.png

# Comment
disqus: wangb
duoshuo:

# Analytics
# google-analytics:
ga: UA-114732129-1

# Copyright Infomation
startyear: 2018
